SiteName: seeta
SiteAddr: BeiJing
Https: true
Nginx:
    Port: 443
    LogPath:  "/var/log//nginx/nginx.log"
    Path: "/opt/nginx/"
Database:
    Port: 3307
    Hostname: ["192.168.80.10","192.168.80.11","192.168.80.12"]
    Username: "clpsadmin"
    Password: "Zq.Am@test1919"

Redis:
    network: "tcp"
    addr: "172.30.7.9"
    port: "6379"
    prefix: ""
mode: "dev"

